// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwzjPsG3JiQO5-sCAvSv4HARAztB34Qu8',
    appId: '1:383903721164:web:329a0604a921f00285c469',
    messagingSenderId: '383903721164',
    projectId: 'utilixa-6ca39',
    authDomain: 'utilixa-6ca39.firebaseapp.com',
    storageBucket: 'utilixa-6ca39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhQHDDxCOVLpYi8ouiTys_OYF0j_gwSJo',
    appId: '1:383903721164:android:3b13505e776a1da085c469',
    messagingSenderId: '383903721164',
    projectId: 'utilixa-6ca39',
    storageBucket: 'utilixa-6ca39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBnKbcf4PHE_jyZZ1t9hWBRc3Xm54H3UA',
    appId: '1:383903721164:ios:0e6593a87c6b7df185c469',
    messagingSenderId: '383903721164',
    projectId: 'utilixa-6ca39',
    storageBucket: 'utilixa-6ca39.firebasestorage.app',
    iosBundleId: 'com.example.utilixa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBnKbcf4PHE_jyZZ1t9hWBRc3Xm54H3UA',
    appId: '1:383903721164:ios:0e6593a87c6b7df185c469',
    messagingSenderId: '383903721164',
    projectId: 'utilixa-6ca39',
    storageBucket: 'utilixa-6ca39.firebasestorage.app',
    iosBundleId: 'com.example.utilixa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwzjPsG3JiQO5-sCAvSv4HARAztB34Qu8',
    appId: '1:383903721164:web:a495c2565108c3eb85c469',
    messagingSenderId: '383903721164',
    projectId: 'utilixa-6ca39',
    authDomain: 'utilixa-6ca39.firebaseapp.com',
    storageBucket: 'utilixa-6ca39.firebasestorage.app',
  );
}
